# Generated by Django 5.0.3 on 2024-04-19 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0002_alter_word_file_alter_word_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="appearance",
        ),
    ]
